### ISSUE TITLE
Loading my own dataset

### ISSUE THREAD

**Issue by arunabh1904** [JindongJiang/RedNet#1]
Hi, 
This is really amazing work. I know its benchmarked with the SUN-RGBD dataset. I want to train my own model with a dataset that I have for a 10 class outdoor semantic segmentation problem. If you could help me figure out the input pipeline for the model I would really appreciate it. I have RGB and Depth Images and I also have classwise labels for each image.( The labels are not .mat files, but png images with classwise pixel-by-pixel labels. Did you have RGB labels or singel channel labels?)Thank you and thank you for sharing this amazing model.

**Comment by arunabh1904** [comment]
Also, in your paper you stated that you train the model with a GTX 1080. Is there a way I could optimize this to use multiple GPU's.

**Comment by arunabh1904** [comment]
Also, I wanted to know how you calculated the median frequency setting for the dataset? The alpha_c factor. Assuming I have 10 ground truth labels. (0 - 9, zero being the background). If I calculate the median freq for the first class, is it going to be the pixel probability of that class in every picture of the dataset divided by the median of the set of all such probabilities?

**Comment by JindongJiang** [comment]
Hi, 

I am so sorry for my late response. 

I figure that the major problem on your dataset is the RGB label. There's a lot of ways to solve this. Let first make sure that the RGB value of a specific class is stationary. Then one way to deal with this label is by using python's dictionary to transfer the RGB value to class (0, 1, ...) for each pixel.

Wrt the second problem. The median prob is actually the median of the prob of all class over all pixels. And the weight is the median prob divided by the prob for that class.

Thank you so much for your interest in our work.

**Comment by arunabh1904** [comment]
Thank you for replying. I have everything set up. I just wanted to know what sized images you trained with this? I have 640*480 images. When I try to train the network I get the Cuda -out of memory error. I want to resize it to the maximum possible size the network can train.

Edit - I fixed the error. But, I am having trouble loading in the data. I have 3 separate image folders each for depth, the raw image and the class-wise labels. Could you help me understand what you have done in the init function in the RedNet_data.py file. My dataset is different from the SUN RGBD dataset and does not contain any metadata.

**Comment by JindongJiang** [comment]
Sure. So, the date reading in RedNet_data.py is for SUNRGBD only and surely different from your dataset. Please ignore the metadata reading process. In your situation, you can simply define lists of the path for each pair of depth, image, and label, then read them in the __call__ function.

Good luck ;)

**Comment by arunabh1904** [comment]
Thanks. I got it working. Really exciting. I had one more question though. How did you get tensorboard running for pytorch?

**Comment by JindongJiang** [comment]
Congratulations! So in order to make tensorboard work, you need to install tensorboardX to write summaries and also tensorflow to run the front end.

**Comment by arunabh1904** [comment]
I have both installed. But, cant seem to run it. I am just pointing tensorboard to the directory where the tensorflow logs are. I am not sure why its not working. Thanks so much for all your help.

**Comment by JindongJiang** [comment]
Sure, no problem. Also, you might want to remove the ` bins='doane'` in `writer.add_histogram`. It may cause errors on the latest tensorboardX and tensorboard.

**Comment by arunabh1904** [comment]
Hi. Thanks. That fixed my tensorboard. I also had to revert back to 1.2. 1.4 has some issues. I wanted to know if you knew a fix for why I cant infer from the saved models. I run the inference files like directed but I get this error " RuntimeError: Error(s) in loading state_dict for RedNet: Missing key(s) in state_dict". Not sure why this is happening only during inference time. Because when I tried loading while training it works just fine. I am still looking into this. Thank you once again for all your help. 

Edit: It seems like when I load it again, it seems to be missing every single key is was supposed to have. Not sure what is causing this.

Edit: Fixed. The keys were misaligning because I had trained the model on multiple GPU's. You mentioned that you in the paper that you trained it on a single Gfx card. Wasn't a big leap. Simple enough fix.

**Comment by JindongJiang** [comment]
I so glad that you fix the problem. And it seems to be very hard to debug and fixed. Good job!

**Comment by arunabh1904** [comment]
Hi. So, Everything in the pipeline is working correctly. I just wanted to know if you are facing the issue I am facing right now. I am solving a 10 class semantic segmentation problem. And, the 10 classes include a background class. In the 1D labels I have generated they are labelled as 0 - 9(0 being the background). In the inferred labels I am getting from the trained network after 1500 epochs, I have zero labels for the background class. I am not sure why this is happening because detecting the background class is of utmost importance. If you have any ideas, I would really appreciate it. Thanks.

**Comment by JindongJiang** [comment]
Hi, by "zero" you mean zero-zero, or very little? And what (customized) loss function do you use?

**Comment by arunabh1904** [comment]
The classes are labelled as 0 , 1 , 2, 3... so on till 9. I converted them from RGB to 1D semantic labels. The loss function that I am using is the same as you. Cross Entropy 2D. Also, there are no images with the zero class inferred.
Edit: Solved.

**Comment by arunabh1904** [comment]
Hi. So, I am trying to add evaluation metrics like pixel accuracy and classwise accuracy and I am having trouble with referencing the tensors. Could you help me with two things.
1. Where are the predictions stored after each training step? How do I access them? I saw the variable pred_scales and it has dimension: 5(for each label in the pyramid)*20(my batch size)*10(num of classes)*width*height. I cant understand how you are extracting the most likely class. 
2. You mention in your paper that you are calculating the mean IOU and other metrics. I cant seem to find them anywhere in the code. Am I missing something? or that part has not been released. Thanks.

**Comment by JindongJiang** [comment]
Hi, sorry for the late response. For part one, to access the prediction you simply need to extract get the slice of the layer of prediction you want to access and use max functions like torch.max() to get the index of the class having the max value which would be the output.

For part two, the evaluations of several metrics are indeed not been released.

**Comment by yjsyic** [comment]
@arunabh1904  Hi,I'm interested in the changes you made to the dataset about rgb depth and label in the code.Can you show me the modified code .Thank you!

**Comment by yjsyic** [comment]
@arunabh1904 Hello, I'm using a dataset whose format is similar to yours. I have had some trouble preprocessing my dataset. Would you please share the codes fitting with your dataset? Thank you very much!
