### ISSUE TITLE
测试效果不太好

### ISSUE THREAD

**Issue by SSTTTAY** [JindongJiang/RedNet#2]
你好，我试了一下用你们预训练出来的模型去测试我的照片。得到的结果是这样：
<img width="1440" alt="2018-09-17 5 09 17" src="https://user-images.githubusercontent.com/26354625/45614547-770ff880-ba9c-11e8-914a-9843f6265ac2.png">
<img width="1440" alt="2018-09-17 5 11 24" src="https://user-images.githubusercontent.com/26354625/45614629-c0604800-ba9c-11e8-9d77-8d528d31f448.png">
它把很多东西都分成了墙，为什么会这样呢？请问你们出来的结果是否有在自己的数据上测试过呢？

**Comment by JindongJiang** [comment]
你好，非常感谢你的反馈，这个问题是存在的。Semantic segmentation的模型在训练集外的其他新场景下的分割效果的确会有较大差异，这个在我们[之前的模型](bit.ly/2pbh7C6)上也出现类似的问题。在我们的其他应用如物体抓取中，一般会制作单个应用专用的数据集，并在该数据集上进行模型的fine tuning。

**Comment by SSTTTAY** [comment]
你好呀，谢谢回复。
我现在在制作自己的数据集。请问你们是用什么工具进行标注的呢？标注完之后的数据格式是怎样的？

**Comment by JindongJiang** [comment]
推荐使用[lableme](https://github.com/wkentaro/labelme/blob/master/README.md)，当然，做image annotation的软件非常多，你也可以寻找其他你们觉得合适的。另外请注意对你的rgb和depth进行对齐。

**Comment by SSTTTAY** [comment]
你好，我想问一下label.npy文件里面装的是 每个像素点对应的种类的图片数组 还是标注信息中 bounding-box的数组。 另外，你说的rgb和depth对齐是指两个图像的文件名要一样吗？

**Comment by JindongJiang** [comment]
你好，label.npy里面每一个位置为该位置所属物体的index，即ground truth。我之前说的rgb和depth对齐是指视场的对齐，如果你们使用Kinect等设备获取rgb与depth，你们会发现两个原图像具有一定的偏差，你们需要对图像进行裁剪从而使得rgb与depth具有精确对齐的视野范围。

**Comment by SSTTTAY** [comment]
你好，我训练自己的数据集的时候如果加入 --cuda使用GPU的话，程序会出现内存不足的错误(我的服务器GPU内存是12G) 

![image](https://user-images.githubusercontent.com/26354625/46709156-f72d1680-cc74-11e8-9456-15ca3087a592.png)

当我去掉--cuda用CPU跑的话，它就一直停在epoch 0那里不动

![image](https://user-images.githubusercontent.com/26354625/46709015-4b83c680-cc74-11e8-8fed-9248ad869c04.png)

请问这是怎么回事？

**Comment by SSTTTAY** [comment]
好吧，把batch_size改为1之后可以了
